version: '3.8'

services:
  api:

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./app:/app

    ports:
      - "8000:8000"

    environment:
      DATABASE_USER: globanTest
      DATABASE_PASS: mypassword
      DATABASE_NAME: employees_jobs
      DATABASE_TYPE: postgresql
      DATABASE_HOST: db
      DATABASE_PORT: 5432

    depends_on:
      - db

  db:

    build: ./database
    image: postgres:latest

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: globanTest
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: employees_jobs
